### ISSUE TITLE
I can't make a request

### ISSUE THREAD

**Issue by the-spanish-guy** [mistweaverco/kulala.nvim#11]
i tried use kulala but when execute `:lua require('kulala').run()` i got error
i use wsl2 with arch

![image](https://github.com/mistweaverco/kulala.nvim/assets/32144508/25a98883-dabc-4be3-8e77-b142a89b7828)

**Comment by gorillamoe** [comment]
I will have a look. In the meantime, what's the output of `nvim --version`?

**Comment by gorillamoe** [comment]
Okay, I booted up a windows machine and installed archlinux via wsl, then I cloned my config and set up neovim. Same error. I tried the appimage, but same error.

I have no clue, maybe it's an issue with neovim itself in conjunction with wsl, because `vim.schedule` is a pretty standard function :shrug:

I will dig a bit into the neovim issues, but I can't guarantee a quick fix.

I might introduce a "quickfix" option in the setup function where you can disable the inlay hints, which is the sole reason I need vim.schedule atm :)

**Comment by gorillamoe** [comment]
Okay, I was quite mislead.. I was thinking of writing to tj if this is a bug in Neovim, but the bug says it can't spawn the process, not the scheduler.. so wildly guessed that might be due to the fact, that you have not installed jq (as I haven't either on windows wsl) .. so that was it.. simply install jq via `sudo pacman -S jq` and you can make requests :)

make sure to have xmllint if you want to have html/xml responses

**Comment by gorillamoe** [comment]
I also pushed a new version where it does at least show the result now, if you don't have a _formatter_ like `jq` or `xmllint` installed.

**Comment by the-spanish-guy** [comment]
it works, txh
