### ISSUE TITLE
Dynamic variables (shared between files) are no longer working

### ISSUE THREAD

**Issue by tompro** [mistweaverco/kulala.nvim#222]
I got a plugin update about 30 minutes ago and for me the support for dynamic env vars seems to be gone:

Given the following request definition:
```
# @name AUTH
POST {{host}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}
```

This follow up request was picking up the correct value:
```
GET {{host}}/restricted/resource
Authorization: Bearer {{AUTH.response.body.$.result.accessToken}}
Accept: application/json
```

Since the update I get the error that the variable is not defined. This is the case even if I use eg. the header of the response. It looks like the top level 'AUTH' variable is not defined.

**Comment by gorillamoe** [comment]
Can you elaborate a bit more, because I checked and document vars, .env, system env and http-client.env.json are all working properly on my side.

We had a breaking change, that is that the variables can't be shared with other http files anymore, they are scoped to the buffer (if you want to have them shared between all files in neovim, you can enable the old behaviour here: https://kulala.mwco.app/docs/getting-started/configuration-options#environment_scope)

**Comment by tompro** [comment]
Ah yes that makes sense. The requests mentioned are in different files. And yes other var sources (env.json) still work fine for me. So did I get this correctly that the request setting the dyn var has to be in the same buffer than the request using it?

**Comment by gorillamoe** [comment]
Yes, except if you want to enable shared data, then the option is for you: https://kulala.mwco.app/docs/getting-started/configuration-options#environment_scope

We did this on purpose to not leak data into other buffers, but if don't mind, you can enable the "old" behaviour.

**Comment by tompro** [comment]
So yes with the global config everything works perfectly well. Thank you for the clarification.
