### ISSUE TITLE
No alternate file after running a request

### ISSUE THREAD

**Issue by Sloff** [mistweaverco/kulala.nvim#289]
After running the requests in an `.http` file with either `require('kulala').run()` or `require('kulala').run_all()`, I get the following error when trying to switch to my previous file: `E23: No alternate file`

**Comment by gorillamoe** [comment]
Can you provide more information about how to reproduce this?

I have a mapping for quickly switching between the current and last opened buffer, which is also broken when using Kulala, but that's my bad, because the keybind is just wrong.

I'm not bothered by it too much, so I haven't bothered fixing it in my setup. Maybe that's also happening for you.

Kulala creates new kulala://ui buffers and deletes old kulala://ui buffers every time it updates the ui.

So maybe you're trying to access an non existent buffer with that "switch to my previous file".

**Comment by Sloff** [comment]
Sure! So in my usual workflow:
- I'll be in some code file to make a change
- Switch to a `.http` file
- Run the request with `require('kulala').run()` (on a keymap)
- After receiving the response, I'll try using CTRL-^ to switch back to the code file, and that's when I get the error message

In my case switching to the previous buffer isn't remapped, I believe CTRL-^ is the default `alternate-file` key mapping.

The code file's buffer is still there if I look at all the open buffers, it's just not the alternate-file anymore, and no other buffer is marked as the alternate-file either (usually indicated with a # in the buffer list)

**Comment by Grueslayer** [comment]
@gorillamoe and it's `Ctrl-6` (`Ctrl-^` does not work on out German keyboards, at least on mine)

**Comment by Sloff** [comment]
Thanks @gorillamoe and @Grueslayer, it's working perfectly!

**Comment by gorillamoe** [comment]
> @gorillamoe and it's `Ctrl-6` (`Ctrl-^` does not work on our German keyboards, at least on mine)

A bit off topic, but I'm [using)(https://gorilla.moe/uses) a [Vortex 10 Limited Edition](https://gorilla.moe/resources/uses/vortex-10-limited-edition.jpg) with US Layout.

I switched to the US Layout like 12 years ago 🤔.
